# Alembic configuration file
# This file supports string interpolation, which allows for using environment
# variables. The convention used here is the `common` format:
#
#    %(here)s
#    %(filename)s

[alembic]
# path to migration scripts
sqlalchemy.url = driver://user:pass@localhost/dbname
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(asctime)s_%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the "revision" timestamp, can be string in alembic.ini style
# or as date.timezone string
# timezone =

# max length of characters to apply to the
# "slug" field in file_template
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# set to 'true' to ignore whitespace-only diffs when
# generating the revision script
# ignore_whitespace = false

# set to true to run "sqlalchemy.create_all()" instead of using
# Alembic to manage schema. This is useful for initial setup.
# sqlalchemy_module_options =
#   sqlalchemy.url=postgresql://user:password@localhost/dbname
#   sqlalchemy.echo=false
#   sqlalchemy.isolation_level=READ COMMITTED

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
