"""Initial migration

Revision ID: 48e367cb9be6
Revises: 
Create Date: 2026-04-11 20:52:16.128365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48e367cb9be6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_habitaciones_id'), table_name='habitaciones')
    op.drop_index(op.f('ix_habitaciones_numero'), table_name='habitaciones')
    op.drop_table('habitaciones')
    op.drop_index(op.f('ix_reservas_habitacion_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_usuario_id'), table_name='reservas')
    op.drop_table('reservas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('habitacion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha_checkin', sa.DATE(), nullable=False),
    sa.Column('fecha_checkout', sa.DATE(), nullable=False),
    sa.Column('num_huespedes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('estado', mysql.ENUM('pendiente', 'activo', 'completado', 'cancelado'), nullable=False),
    sa.Column('solicitudes_especiales', mysql.TEXT(), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['habitacion_id'], ['habitaciones.id'], name=op.f('reservas_ibfk_2')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('reservas_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_reservas_usuario_id'), 'reservas', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    op.create_index(op.f('ix_reservas_habitacion_id'), 'reservas', ['habitacion_id'], unique=False)
    op.create_table('habitaciones',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('numero', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('tipo', mysql.ENUM('comun', 'familiar', 'premium', 'suite'), nullable=False),
    sa.Column('capacidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('precio_noche', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('estado', mysql.ENUM('libre', 'ocupado', 'mantenimiento'), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('amenidades', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_habitaciones_numero'), 'habitaciones', ['numero'], unique=True)
    op.create_index(op.f('ix_habitaciones_id'), 'habitaciones', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('rol', mysql.ENUM('admin', 'huesped'), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###
